---
abstract: 'Dive XML with XML and first-class collection + alpha'
author:
  - 'ytnobody <ytnobody@gmail.com>'
build_requires:
  File::Spec: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.5, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Diver
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  XML::Diver:
    file: lib/XML/Diver.pm
    version: 0.01
requires:
  Class::Builtin: 0.05
  XML::LibXML: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/ytnobody/XML-Diver/issues
  homepage: https://github.com/ytnobody/XML-Diver
  repository: git://github.com/ytnobody/XML-Diver.git
version: 0.01
x_authority: cpan:YTURTLE
